// Mane Concept hair color swatch map — hotlinkable, no text overlay
// Source: maneconcepthair.com/color-chart
const BASE = 'https://www.maneconcepthair.com/media/wysiwyg/collateral/colors'

const SWATCHES: Record<string, string> = {
  '1':             `${BASE}/DARK/SOLID/1.jpg`,
  '1B':            `${BASE}/DARK/SOLID/1B.jpg`,
  '2':             `${BASE}/DARK/SOLID/2.jpg`,
  '4':             `${BASE}/BROWN/SOLID/4.jpg`,
  '6':             `${BASE}/BROWN/SOLID/6.jpg`,
  '8':             `${BASE}/BROWN/SOLID/8.jpg`,
  '27':            `${BASE}/BROWN/SOLID/27.jpg`,
  '30':            `${BASE}/BROWN/SOLID/30.jpg`,
  '33':            `${BASE}/BROWN/SOLID/33.jpg`,
  '350':           `${BASE}/RED/SOLID/350.jpg`,
  '612':           `${BASE}/BLONDE/SOLID/612.jpg`,
  '613':           `${BASE}/BLONDE/SOLID/613.jpg`,
  '99J':           `${BASE}/RED/SOLID/99J.jpg`,
  'RED':           `${BASE}/RED/SOLID/RED.jpg`,
  'NATURAL':       `${BASE}/DARK/SOLID/NATURAL.jpg`,
  'N.BLACK':       `${BASE}/DARK/SOLID/N.BLACK.jpg`,
  'BLACKSILVER':   `${BASE}/GRAY/SOLID/BLACKSILVER.jpg`,
  'PLATINUMGREY':  `${BASE}/GRAY/SOLID/PLATINUMGREY.jpg`,
  'DIORGREY':      `${BASE}/GRAY/SOLID/DIORGREY.jpg`,
  'MAUVE':         `${BASE}/GRAY/SOLID/MAUVE.jpg`,
  'MAUVEWINE':     `${BASE}/GRAY/SOLID/MAUVEWINE.jpg`,
  'BLUSHBLOND':    `${BASE}/BLONDE/SOLID/BLUSHBLOND.jpg`,
  'ICYBLOND':      `${BASE}/BLONDE/SOLID/ICYBLOND.jpg`,
  'CHESTNUTBROWN': `${BASE}/BROWN/SOLID/CHESTNUTBROWN.jpg`,
  'MAHOGANYBROWN': `${BASE}/BROWN/SOLID/MAHOGANYBROWN.jpg`,
  'DEEPRED':       `${BASE}/RED/SOLID/DEEPRED.jpg`,
  'REDBLACK':      `${BASE}/RED/SOLID/REDBLACK.jpg`,
  'REDWINE':       `${BASE}/RED/SOLID/REDWINE.jpg`,
  'RUBYROSE':      `${BASE}/RED/SOLID/RUBYROSE.jpg`,
  'SCARLET':       `${BASE}/RED/SOLID/SCARLET.jpg`,
  'CANDYAPPLE':    `${BASE}/RED/SOLID/CANDYAPPLE.jpg`,
  'FIESTA':        `${BASE}/RED/SOLID/FIESTA.jpg`,
  'BUG':           `${BASE}/RED/SOLID/BUG.jpg`,
  'NEONRED':       `${BASE}/RED/SOLID/NEONRED.jpg`,
  'NEONRUST':      `${BASE}/RED/SOLID/NEONRUST.jpg`,
  'FADEDENIM':     `${BASE}/DARK/SOLID/FADEDENIM.jpg`,
  'AQUA':          `${BASE}/BRILLIANT/SOLID/AQUA.jpg`,
  'ASPENGOLD':     `${BASE}/BRILLIANT/SOLID/ASPENGOLD.jpg`,
  'ATLANTIC':      `${BASE}/BRILLIANT/SOLID/ATLANTIC.jpg`,
  'BLORANGE':      `${BASE}/BRILLIANT/SOLID/BLORANGE.jpg`,
  'BLUSHROSE':     `${BASE}/BRILLIANT/SOLID/BLUSHROSE.jpg`,
  'CIDER':         `${BASE}/BRILLIANT/SOLID/CIDER.jpg`,
  'DEEPBLUE':      `${BASE}/BRILLIANT/SOLID/DEEPBLUE.jpg`,
  'DEEPGREEN':     `${BASE}/BRILLIANT/SOLID/DEEPGREEN.jpg`,
  'DEEPPURPLE':    `${BASE}/BRILLIANT/SOLID/DEEPPURPLE.jpg`,
  'DENIMBLUE':     `${BASE}/BRILLIANT/SOLID/DENIMBLUE.jpg`,
  'DEWBERRY':      `${BASE}/BRILLIANT/SOLID/DEWBERRY.jpg`,
  'GRAPE':         `${BASE}/BRILLIANT/SOLID/GRAPE.jpg`,
  'ICEBLUE':       `${BASE}/BRILLIANT/SOLID/ICEBLUE.jpg`,
  'INDIGOBLUE':    `${BASE}/BRILLIANT/SOLID/INDIGOBLUE.jpg`,
  'JEANBLUE':      `${BASE}/BRILLIANT/SOLID/JEANBLUE.jpg`,
  'LEMONPIE':      `${BASE}/BRILLIANT/SOLID/LEMONPIE.jpg`,
  'LIVINGCORAL':   `${BASE}/BRILLIANT/SOLID/LIVINGCORAL.jpg`,
  'NAVYBLUE':      `${BASE}/BRILLIANT/SOLID/NAVYBLUE.jpg`,
  'NEONBLUE':      `${BASE}/BRILLIANT/SOLID/NEONBLUE.jpg`,
  'NEONCOBALT':    `${BASE}/BRILLIANT/SOLID/NEONCOBALT.jpg`,
  'NEONGRAPE':     `${BASE}/BRILLIANT/SOLID/NEONGRAPE.jpg`,
  'NEONGREEN':     `${BASE}/BRILLIANT/SOLID/NEONGREEN.jpg`,
  'NEONGUAVA':     `${BASE}/BRILLIANT/SOLID/NEONGUAVA.jpg`,
  'NEONICEBLUE':   `${BASE}/BRILLIANT/SOLID/NEONICEBLUE.jpg`,
  'NEONLEMON':     `${BASE}/BRILLIANT/SOLID/NEONLEMON.jpg`,
  'NEONLIME':      `${BASE}/BRILLIANT/SOLID/NEONLIME.jpg`,
  'NEONMINT':      `${BASE}/BRILLIANT/SOLID/NEONMINT.jpg`,
  'NEONORANGE':    `${BASE}/BRILLIANT/SOLID/NEONORANGE.jpg`,
  'NEONPASTEL':    `${BASE}/BRILLIANT/SOLID/NEONPASTEL.jpg`,
  'NEONPINK':      `${BASE}/BRILLIANT/SOLID/NEONPINK.jpg`,
  'NEONSOL':       `${BASE}/BRILLIANT/SOLID/NEONSOL.jpg`,
  'NEONTURQ':      `${BASE}/BRILLIANT/SOLID/NEONTURQ.jpg`,
  'NEONYELLOW':    `${BASE}/BRILLIANT/SOLID/NEONYELLOW.jpg`,
  'ORANGEBLAZE':   `${BASE}/BRILLIANT/SOLID/ORANGEBLAZE.jpg`,
  'PALEPINK':      `${BASE}/BRILLIANT/SOLID/PALEPINK.jpg`,
  'PEACH':         `${BASE}/BRILLIANT/SOLID/PEACH.jpg`,
  'PEACHPINK':     `${BASE}/BRILLIANT/SOLID/PEACHPINK.jpg`,
  'PLUM':          `${BASE}/BRILLIANT/SOLID/PLUM.jpg`,
  'PRESSEDROSE':   `${BASE}/BRILLIANT/SOLID/PRESSEDROSE.jpg`,
  'PRUSSIANBLUE':  `${BASE}/BRILLIANT/SOLID/PRUSSIANBLUE.jpg`,
  'PUMPKINSPICE':  `${BASE}/BRILLIANT/SOLID/PUMPKINSPICE.jpg`,
  'PURPLEBLACK':   `${BASE}/BRILLIANT/SOLID/PURPLEBLACK.jpg`,
  'SOFTPINK':      `${BASE}/BRILLIANT/SOLID/SOFTPINK.jpg`,
}

/** Returns a swatch image URL for a color code, or null if not in the map. */
export function getSwatchUrl(colorCode: string): string | null {
  if (!colorCode) return null
  const key = colorCode.trim().toUpperCase()
  return SWATCHES[key] ?? null
}
